channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - conda-forge::python=3.11
  - conda-forge::numpy=1.25.2
  - conda-forge::matplotlib=3.7.2
  - conda-forge::tqdm=4.66.1
  - conda-forge::ipykernel=6.25.1
  - conda-forge::scikit-learn=1.3.0
  - conda-forge::pytorch-lightning=2.0.7
  - conda-forge::tensorboard=2.14.0
  - conda-forge::torchmetrics=1.0.3
  - pytorch::pytorch=2.0.1
  - pytorch::pytorch-cuda=11.7
  - pip:
      - torch-tb-profiler==0.4.1