name: transformer
channels:
  - conda-forge
dependencies:
  - conda-forge::python=3.11
  - pip
  - pip:
    - numpy==2.1.2
    - matplotlib==3.9.2
    - tqdm==4.66.5
    - ipykernel==6.29.5
    - ipywidgets==8.1.5
    - torch==2.4.1
    - torchvision
    - torchaudio
    - transformers==4.45.2